### ISSUE TITLE
请教术语表

### ISSUE THREAD

**Issue by forthemoon2026** [YanMing-lxb/SCI-LaTeX-Submission-Process-for-Elsevier#2]
感谢大佬付出。

想请教下，为啥正文没有写\printnomenclature，依然可以输出术语表。

祝好。

**Comment by YanMing-lxb** [comment]
我在 CN-Manuscript.tex 中的前言区自定义了命令 `\newcommand{\Nomenclature}{\input{\Process/Section/Nomenclature}}`  
并在 `Nomenclature.tex` 文件中放置了 `\printnomenclature[23mm]` 命令，最后在 Section1 中应用 `\Nomenclature` 命令。

下面是我在 `CN-Manuscript.tex` 中自定义的命令：

```tex
% -----------------------------------------------------
%                        自定义命令                     *******************************************************
% -----------------------------------------------------
\newcommand{\Process}{1-Manuscript-CN}
\graphicspath{{\Process/Pictures/},}                                   % 图片所在文件夹，可放置多个文件夹，用,分隔。
\newcommand{\Nomenclature}{\input{\Process/Section/Nomenclature}}      % 定义新命令
```
说来惭愧，这是一个很笨的方法，有时我也感觉有点多余。

**Comment by forthemoon2026** [comment]
抱歉，昨天看的时候没有看到，打扰您了，感谢您的细心回复。

代码模块化，很清爽。

祝好。

**Comment by Rowan0058** [comment]
请问大佬，环境graphicalabstract是latex中原本有的吗，为什么运行后显示未定义呢
![image](https://github.com/YanMing-lxb/SCI-LaTeX-Submission-Process-for-Elsevier/assets/152239613/e551fdc7-c771-400c-b2eb-c786dd13e937)

**Comment by YanMing-lxb** [comment]
```
    \begin{graphicalabstract}
        \centering
        \includegraphics*[width=1 \textwidth]{Schematic.jpg}
    \end{graphicalabstract}
```
`graphicalabstract` 环境是 `alsarticle` 文档类自定义的环境类型，你检查一下你输入的拼写有没有错误，你写的代码有没有错误。常规来说文档类的定义是不会有错了，有时候报错不一定准确，你仔细检查一下吧

**Comment by Rowan0058** [comment]
是我拼写有误，非常感谢您的回复。
