### ISSUE TITLE
术语表请教

### ISSUE THREAD

**Issue by Rowan0058** [YanMing-lxb/SCI-LaTeX-Submission-Process-for-Elsevier#3]
大佬您好，请问为什么码好程序运行后出现这样的警告，双击警告跳转到Nomenclature.tex文件，而且运行后文章中没有术语表显示
![image](https://github.com/YanMing-lxb/SCI-LaTeX-Submission-Process-for-Elsevier/assets/152239613/b2f51cf1-567c-41c9-8945-bd28aed28066)

**Comment by YanMing-lxb** [comment]
是编译链的问题，makeindex 是用于编译目录的，而nomencl需要在 makeindex 命令后单独添加命令 
如：`"makeindex", "-s", "nomencl.ist", "-o", f"{file_name}.nls", f"{file_name}.nlo"`

你看一下我的另一个项目 [YM VSCode Configurations for LaTeX](https://github.com/YanMing-lxb/YM-VSCode-Configurations-for-LaTeX) 中对 `latexmk` 的配置说明，建议使用 `latexmk` 进行编译（省事一些）。
（当然也可以用我在https://github.com/YanMing-lxb/GUET_Thesis_LaTeX 项目中用的makefile.py、makefile.bat文件编译，前提要安装python。）

**Comment by Rowan0058** [comment]
明白了，在使用makeindex命令后成功解决问题
